// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg7FiPiVlloJA0BrDjUZKbgsRcwHoYSPU',
    appId: '1:450892632554:web:265e492e0bfa5fede36293',
    messagingSenderId: '450892632554',
    projectId: 'obesight',
    authDomain: 'obesight.firebaseapp.com',
    storageBucket: 'obesight.firebasestorage.app',
    measurementId: 'G-VLQCQJCWKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJdEY9u-dfT6LCNKYuWUnzq37-51t45yo',
    appId: '1:450892632554:android:884fc1e64bc1b935e36293',
    messagingSenderId: '450892632554',
    projectId: 'obesight',
    storageBucket: 'obesight.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGx2YZzpCNHxoe9GX5DLFND2Mgpnxe0CQ',
    appId: '1:450892632554:ios:34f1a6ac4e126b44e36293',
    messagingSenderId: '450892632554',
    projectId: 'obesight',
    storageBucket: 'obesight.firebasestorage.app',
    iosBundleId: 'com.obesight.obesight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGx2YZzpCNHxoe9GX5DLFND2Mgpnxe0CQ',
    appId: '1:450892632554:ios:34f1a6ac4e126b44e36293',
    messagingSenderId: '450892632554',
    projectId: 'obesight',
    storageBucket: 'obesight.firebasestorage.app',
    iosBundleId: 'com.obesight.obesight',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg7FiPiVlloJA0BrDjUZKbgsRcwHoYSPU',
    appId: '1:450892632554:web:4f6be137df8f97e2e36293',
    messagingSenderId: '450892632554',
    projectId: 'obesight',
    authDomain: 'obesight.firebaseapp.com',
    storageBucket: 'obesight.firebasestorage.app',
    measurementId: 'G-H3QZ6E999S',
  );
}
